# Generated by Django 5.2.1 on 2025-06-03 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(4, message='ФИО должно содержать минимум 4 символа'), django.core.validators.RegexValidator(message='Имя может содержать только русские, английские буквы, символы Ң ң, Ө ө, Ү ү и дефис', regex='^[а-яА-ЯёЁa-zA-ZҢңӨөҮү\\s\\-]+$')], verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона начинается с +996 и должен содержать 9 цифр после кода страны(Пример: +996 700123456)', regex='^\\+996(22\\d|55\\d|70\\d|99\\d|77\\d|54\\d|51\\d|57\\d|56\\d|50\\d)\\d{6}$')], verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('visited', 'Посещена'), ('no_show', 'Неявка'), ('cancelled_by_patient', 'Отменена пациентом'), ('cancelled_by_admin', 'Отменена админом'), ('rescheduled', 'Перенос'), ('completed_with_treatment', 'Завершено с назначением лечения')], default='scheduled', verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Описание')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctor.doctor', verbose_name='Врач')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='doctor.timeslot', verbose_name='Временной слот')),
                ('treatment_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_appointment', to='patient.appointment', verbose_name='Назначенное лечение')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.profile', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(validators=[django.core.validators.MinLengthValidator(5, message='Минимальная длина отзыва - 10 символов'), django.core.validators.MaxLengthValidator(500, message='Максимальная длина отзыва - 500 символов')], verbose_name='Комментарий')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка - 1'), django.core.validators.MaxValueValidator(5, message='Максимальная оценка - 5')], verbose_name='Оценка')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment', verbose_name='Приём')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.profile', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона начинается с +996 и должен содержать 9 цифр после кода страны(Пример: +996 700123456)', regex='^\\+996(22\\d|55\\d|70\\d|99\\d|77\\d|54\\d|51\\d|57\\d|56\\d|50\\d)\\d{6}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('message_type', models.CharField(choices=[('appointment_created', 'Заявка создана'), ('appointment_reminder', 'Напоминание о записи'), ('registration_code', 'Код подтверждения'), ('registration_success', 'Успешная регистрация'), ('appointment_confirmation', 'Подтверждение записи'), ('appointment_cancellation', 'Отмена записи'), ('treatment_assigned', 'Назначено лечение')], max_length=50, verbose_name='Тип сообщения')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('pending', 'В ожидании'), ('failed', 'Не доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patient.appointment', verbose_name='Приём')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patient.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['profile', '-sent_at'], name='patient_not_profile_215bad_idx'), models.Index(fields=['appointment', 'message_type'], name='patient_not_appoint_f1c5c1_idx'), models.Index(fields=['phone_number', 'message_type'], name='patient_not_phone_n_e00e33_idx'), models.Index(fields=['verification_code'], name='patient_not_verific_122d97_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'time_slot'), name='unique_doctor_time_slot'),
        ),
    ]
