# Generated by Django 5.2.1 on 2025-06-12 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_profile_is_guest_profile_username_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной'), django.core.validators.MaxValueValidator(100000, message='Цена не может превышать 100 000')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона начинается с +996 и должен содержать 9 цифр после кода страны(Пример: +996 700123456)', regex='^\\+996(22\\d|55\\d|70\\d|99\\d|77\\d|54\\d|51\\d|57\\d|56\\d|50\\d)\\d{6}$')], verbose_name='Номер телефона'),
        ),
    ]
