# Generated by Django 5.2.1 on 2025-06-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_appointment_price_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий гостя'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя гостя'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон гостя'),
        ),
    ]
