# Generated by Django 5.2.1 on 2025-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='days_of_week',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, verbose_name='День недели'),
            preserve_default=False,
        ),
    ]
