# Generated by Django 5.2.1 on 2025-06-06 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_scheduletemplate_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'ordering': ['doctor', 'day_of_week'], 'verbose_name': 'Шаблон расписания', 'verbose_name_plural': 'Шаблоны расписания'},
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания работы'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='templatetimeslot',
            name='duration',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (минут)'),
        ),
        migrations.AlterField(
            model_name='templatetimeslot',
            name='slot_type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('treatment', 'Лечение')], default='consultation', max_length=20, verbose_name='Тип слота'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (минут)'),
        ),
    ]
