# Generated by Django 5.2.1 on 2025-06-06 18:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_scheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'verbose_name': 'Шаблон расписания', 'verbose_name_plural': 'Шаблоны расписания'},
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_templates', to='doctor.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='end_time',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='start_time',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='templatetimeslot',
            name='duration',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(55)], verbose_name='Длительность (минут)'),
        ),
        migrations.AlterField(
            model_name='templatetimeslot',
            name='slot_type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('treatment', 'Лечение')], max_length=20, verbose_name='Тип слота'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(55)], verbose_name='Длительность (минут)'),
        ),
    ]
