# Generated by Django 5.2.1 on 2025-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_scheduletemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='generation_period_days',
            field=models.IntegerField(default=30, verbose_name='Период генерации слотов (дней)'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='last_slot_generation',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя генерация слотов'),
        ),
    ]
