# Generated by Django 5.2.1 on 2025-06-06 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_scheduletemplate_generation_period_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'ordering': ['doctor', 'day_of_week'], 'verbose_name': 'Шаблон расписания', 'verbose_name_plural': 'Шаблоны расписания'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'default_manager_name': 'objects', 'ordering': ['date', 'start_time'], 'permissions': [('can_manage_slots', 'Can manage time slots')], 'verbose_name': 'Временной слот', 'verbose_name_plural': 'Временные слоты'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='generation_period_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Период генерации слотов (дней)'),
        ),
    ]
