# Generated by Django 5.2.1 on 2025-06-12 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='full_bio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Полная биография не должна превышать 1000 символов')], verbose_name='Полная биография'),
        ),
    ]
