# Generated by Django 5.2.1 on 2025-06-15 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctor_full_bio'),
        ('patient', '0004_appointment_guest_comment_appointment_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='Биография не должна превышать 1000 символов')], verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='generation_period_days',
            field=models.IntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Период генерации слотов (дней)'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default='active', help_text='Выберите статус лечения', max_length=30, verbose_name='Статус')),
                ('diagnosis', models.CharField(help_text='Введите диагноз болезни (5-50 символов)', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Диагноз')),
                ('treatment_plan', models.TextField(help_text='Введите план лечения (10-2000 символов)', max_length=2000, validators=[django.core.validators.MinLengthValidator(10, message='План лечения должен содержать минимум 10 символов'), django.core.validators.RegexValidator(message='План лечения может содержать только русские, английские буквы, символы Ң ң, Ө ө, Ү ү, точки, запятые, восклицательные и вопросительные знаки, скобки и дефис', regex='^[а-яА-ЯёЁa-zA-ZҢңӨөҮү\\s.,!?()-]+$')], verbose_name='План лечения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatments', to='doctor.doctor')),
                ('initial_appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatments', to='patient.profile')),
            ],
            options={
                'verbose_name': 'История болезни',
                'verbose_name_plural': 'Истории болезни',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Заметки о сессии могут содержать максимум 4000 символов', max_length=4000, validators=[django.core.validators.RegexValidator(message='Заметки могут содержать только буквы, цифры и знаки препинания', regex='^[а-яА-ЯёЁa-zA-Z0-9\\s.,!?()-]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctor.treatment')),
            ],
            options={
                'verbose_name': 'Сессия лечения',
                'verbose_name_plural': 'Сессии лечения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Максимальный размер фотографии 10мб, форматы: jpg, jpeg, png', upload_to='treatment_photos/%Y%m%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Разрешены только форматы: jpg, jpeg, png')])),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='doctor.treatmentsession')),
            ],
        ),
    ]
