# Generated by Django 5.2.1 on 2025-06-19 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio_ky',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200, message='Биография не должна превышать 1000 символов')], verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200, message='Биография не должна превышать 1000 символов')], verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_ky',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Полная биография не должна превышать 1000 символов')], verbose_name='Полная биография'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_bio_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000, message='Полная биография не должна превышать 1000 символов')], verbose_name='Полная биография'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='description_specialization_ky',
            field=models.TextField(null=True, verbose_name='Описание специализации'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='description_specialization_ru',
            field=models.TextField(null=True, verbose_name='Описание специализации'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_specialization_ky',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название специализации'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_specialization_ru',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название специализации'),
        ),
    ]
